name: Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: udpate apt
        run: sudo apt-get update
      - name: install apt dependencies
        run: sudo apt-get install -y xvfb firefox chromium-browser
      - name: install dependencies
        run: npm ci
      - name: test package
        run: npm test
      - name: build package
        run: npm run build
